-- Run this script in Supabase SQL Editor.
create extension if not exists "pgcrypto";
create type product_status as enum ('draft', 'published', 'archived');
create table if not exists products (
  id bigint generated by default as identity primary key,
  seller_id uuid references auth.users(id) on delete set null,
  name text not null, slug text unique not null, category text not null,
  description text not null default '', price integer not null check (price >= 0),
  image_url text, download_url text, status product_status not null default 'draft',
  created_at timestamptz not null default now()
);
create table if not exists orders (
  id uuid primary key default gen_random_uuid(), stripe_session_id text unique not null,
  stripe_payment_intent_id text, email text, product_id bigint references products(id),
  amount integer not null default 0, status text not null default 'paid', created_at timestamptz not null default now()
);
alter table products enable row level security;
create policy "Published products are public" on products for select using (status = 'published');
create policy "Sellers manage own products" on products for all using (auth.uid() = seller_id) with check (auth.uid() = seller_id);
