export type Product = { id: number; slug: string; name: string; category: string; creator: string; price: number; originalPrice: number; rating: number; description: string; tags: string[]; image: string };
export const productCategories = ['Branding', 'UI Kits', 'Templates', 'Mockups', 'Social', 'Printables'];
export const products: Product[] = [
{id:1,slug:'brand-launch-kit',name:'Brand Launch Kit',category:'Branding',creator:'Luna Studio',price:39,originalPrice:79,rating:4.9,description:'A complete brand identity system for startups and small businesses, featuring logos, typography, color systems, and social templates.',tags:['brand kit','logo','packaging','social'],image:'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80'},
{id:2,slug:'launchpad-ui-kit',name:'LaunchPad UI Kit',category:'UI Kits',creator:'North Pixel',price:59,originalPrice:99,rating:5,rating:5,description:'High-converting SaaS landing page components and interface elements built for modern product teams.',tags:['saas','figma','landing page','ui'],image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80'},
{id:3,slug:'social-growth-pack',name:'Social Growth Pack',category:'Templates',creator:'Margot Labs',price:29,originalPrice:49,rating:4.8,description:'Editable templates for Instagram, TikTok, and LinkedIn content designed to increase engagement and brand consistency.',tags:['social','content','marketing','reels'],image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80'},
{id:4,slug:'minimal-product-mockups',name:'Minimal Product Mockups',category:'Mockups',creator:'Aster House',price:34,originalPrice:69,rating:4.7,description:'Photorealistic, light-filled mockup scenes for digital products, packaging, and print-based marketing campaigns.',tags:['mockup','packaging','product','studio'],image:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80'},
{id:5,slug:'creator-content-system',name:'Creator Content System',category:'Social',creator:'Harlow Studio',price:26,originalPrice:48,rating:4.9,description:'A polished bundle of content templates, hooks, brand presets, thumbnails, and post layouts for creators.',tags:['creator','content','reels','workflow'],image:'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=1200&q=80'},
{id:6,slug:'printable-workshop-kit',name:'Printable Workshop Kit',category:'Printables',creator:'Moss Avenue',price:24,originalPrice:42,rating:4.8,description:'Planner, worksheet, and journal templates for coaches, consultants, and service businesses.',tags:['planner','prints','workshop','template'],image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80'}
];
